In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


from keras.layers.core import Dense, Activation, Dropout
from keras.layers.recurrent import LSTM
from keras.models import Sequential
from keras.callbacks import ModelCheckpoint
from keras.models import load_model
from keras.optimizers import Adam
from keras.regularizers import l2

import sys

In [11]:
#functions
def mse_loss(y_predict, y):
    return np.mean(np.square(y_predict - y)) 

def mae_loss(y_predict, y):
    return np.mean(np.abs(y_predict - y)) 

def build_nn_model(layers):
    nn_model = Sequential()
    for i in range(len(layers)-1):
        nn_model.add( Dense(input_dim=layers[i], output_dim= layers[i+1]) )#, W_regularizer=l2(0.1)) )
        nn_model.add( Dropout(0.5) )
        if i < (len(layers) - 2):
            nn_model.add( Activation('relu') )
    print(nn_model.summary())
    return nn_model

In [12]:
def plot_each_app(df, num_date, predict, y_test, title, look_back = 0):
    num_date = len(dates)
    fig, axes = plt.subplots(num_date,1,figsize=(24, num_date*5) )
    plt.suptitle(title, fontsize = '25')
    fig.tight_layout()
    fig.subplots_adjust(top=0.95)
    for i in range(num_date):
        if i == 0: l = 0
        ind = df.ix[dates[i]].index[look_back:]
        axes.flat[i].plot(ind, y_test[l:l+len(ind)], color = 'blue', alpha = 0.6, label = 'True value')
        axes.flat[i].plot(ind, predict[l:l+len(ind)], color = 'red', alpha = 0.6, label = 'Predicted value')
        axes.flat[i].legend()
        l = len(ind)

In [20]:
app =  'microwave_11' #'refrigerator_5'
path = 'train_test_data/'

#read data
df_train = pd.read_csv(path+'H1_train.csv')
df_val = pd.read_csv(path+'H1_val.csv')
df_test = pd.read_csv(path+'H1_test.csv')

#turn first column into date_time index
df_list = [df_train, df_val, df_test]
for df in df_list:
    df['timestamp'] = pd.to_datetime(df['Unnamed: 0'])
    df = df.set_index('timestamp')
    
X_train1 = df_train[['mains_1','mains_2']].values
y_train1 = df_train[app].values
X_val1 = df_val[['mains_1','mains_2']].values
y_val1 = df_val[app].values
X_test1 = df_test[['mains_1','mains_2']].values
y_test1 = df_test[app].values

In [5]:
#setting parameters
input_dim = 2
layer1_dim = 64
layer2_dim = 128
output_dim = 1

#Constructing Neural Network
layers = [input_dim, layer1_dim, layer2_dim, output_dim]
fc_model_1 = build_nn_model(layers)

adam = Adam(lr = 0.001)
fc_model_1.compile(loss='mean_squared_error', optimizer=adam)

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_1 (Dense)              (None, 64)                192
_________________________________________________________________
dropout_1 (Dropout)          (None, 64)                0
_________________________________________________________________
activation_1 (Activation)    (None, 64)                0
_________________________________________________________________
dense_2 (Dense)              (None, 128)               8320
_________________________________________________________________
dropout_2 (Dropout)          (None, 128)               0
_________________________________________________________________
activation_2 (Activation)    (None, 128)               0
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 129
_________________________________________________________________
dropout_3 (Dropout)          (None, 1)                 0
=================================================================
Total params: 8,641
Trainable params: 8,641
Non-trainable params: 0
_________________________________________________________________
None

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=2, units=64)`
  # This is added back by InteractiveShellApp.init_path()
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=64, units=128)`
  # This is added back by InteractiveShellApp.init_path()
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=128, units=1)`
  # This is added back by InteractiveShellApp.init_path()

In [ ]:
hist_fc_1 = fc_model_1.fit( X_train1, y_train1,
                    batch_size=512, verbose=1, nb_epoch=100,
                    validation_split=0.33)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  This is separate from the ipykernel package so we can avoid doing imports until

Train on 143926 samples, validate on 70890 samples
Epoch 1/100

In [15]:
pd.DataFrame(y_test1).head()

     0
0  4.0
1  4.0
2  4.0
3  4.0
4  4.0

In [16]:
test = pd.DataFrame()

In [22]:
test = pd.DataFrame()
test['time'] = df_test['Unnamed: 0']
test['y_true'] = y_test1
test.head()

   y_true                 time
0     4.0  2011-05-11 07:19:47
1     4.0  2011-05-11 07:20:08
2     4.0  2011-05-11 07:20:17
3     4.0  2011-05-11 07:20:20
4     4.0  2011-05-11 07:20:24

In [21]:
df_test

,Unnamed: 0,mains_1,mains_2,oven_3,oven_4,refrigerator_5,dishwaser_6,kitchen_outlets_7,kitchen_outlets_8,lighting_9,...,bathroom_gfi_12,electric_heat_13,stove_14,kitchen_outlets_15,kitchen_outlets_16,lighting_17,lighting_18,washer_dryer_19,washer_dryer_20,timestamp
0,2011-05-11 07:19:47,97.52,38.38,0.0,0.0,6.0,0.0,23.0,20.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:19:47
1,2011-05-11 07:20:08,95.61,38.29,0.0,0.0,7.0,0.0,21.0,20.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:20:08
2,2011-05-11 07:20:17,94.86,38.56,0.0,0.0,7.0,0.0,22.0,20.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:20:17
3,2011-05-11 07:20:20,95.21,38.29,0.0,0.0,6.0,0.0,24.0,21.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:20:20
4,2011-05-11 07:20:24,95.82,38.35,0.0,0.0,7.0,0.0,22.0,20.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:20:24
5,2011-05-11 07:20:27,94.78,38.57,0.0,0.0,7.0,0.0,22.0,20.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:20:27
6,2011-05-11 07:20:31,94.58,38.16,0.0,0.0,7.0,0.0,21.0,21.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:20:31
7,2011-05-11 07:20:34,95.03,38.30,0.0,0.0,7.0,0.0,21.0,21.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:20:34
8,2011-05-11 07:20:38,99.15,38.54,0.0,0.0,6.0,0.0,26.0,20.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:20:38
9,2011-05-11 07:20:41,97.72,38.26,0.0,0.0,7.0,0.0,24.0,20.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:20:41
10,2011-05-11 07:20:45,98.07,38.58,0.0,0.0,7.0,0.0,24.0,21.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:20:45
11,2011-05-11 07:20:48,97.99,38.42,0.0,0.0,7.0,0.0,24.0,20.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:20:48
12,2011-05-11 07:20:51,100.84,38.32,0.0,0.0,6.0,0.0,26.0,20.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,2011-05-11 07:20:51
13,2011-05-11 07:20:55,95.52,38.59,0.0,0.0,7.0,0.0,22.0,21.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:20:55
14,2011-05-11 07:20:58,94.65,38.58,0.0,0.0,7.0,0.0,25.0,20.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:20:58
15,2011-05-11 07:21:02,95.44,38.41,0.0,0.0,7.0,0.0,21.0,21.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:21:02
16,2011-05-11 07:21:05,95.15,38.48,0.0,0.0,6.0,0.0,22.0,21.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,2011-05-11 07:21:05
17,2011-05-11 07:21:09,95.91,38.34,0.0,0.0,7.0,0.0,24.0,20.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:21:09
18,2011-05-11 07:21:18,95.62,38.28,0.0,0.0,7.0,0.0,22.0,20.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:21:18
19,2011-05-11 07:21:21,95.51,38.24,0.0,0.0,7.0,0.0,22.0,20.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:21:21
20,2011-05-11 07:21:24,95.84,38.47,0.0,0.0,7.0,0.0,24.0,20.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:21:24
21,2011-05-11 07:21:28,95.52,38.49,0.0,0.0,7.0,0.0,24.0,20.0,42.0,...,1.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:21:28
22,2011-05-11 07:21:31,98.30,38.27,0.0,0.0,7.0,0.0,26.0,20.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:21:31
23,2011-05-11 07:21:35,98.40,38.38,0.0,0.0,7.0,0.0,22.0,20.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:21:35
24,2011-05-11 07:21:38,98.60,38.39,0.0,0.0,7.0,0.0,24.0,20.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:21:38
25,2011-05-11 07:21:42,99.67,38.45,0.0,0.0,7.0,0.0,25.0,21.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:21:42
26,2011-05-11 07:21:45,100.36,38.41,0.0,0.0,7.0,0.0,26.0,20.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:21:45
27,2011-05-11 07:21:49,97.77,38.28,0.0,0.0,7.0,0.0,23.0,21.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:21:49
28,2011-05-11 07:21:52,98.43,38.40,0.0,0.0,7.0,0.0,25.0,21.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:21:52
29,2011-05-11 07:21:56,100.13,38.38,0.0,0.0,7.0,0.0,27.0,20.0,42.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-11 07:21:56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87027,2011-05-24 18:31:14,240.90,38.20,0.0,0.0,194.0,0.0,20.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 18:31:14
87028,2011-05-24 18:31:18,242.28,38.30,0.0,0.0,198.0,1.0,23.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 18:31:18
87029,2011-05-24 18:31:21,243.20,37.99,0.0,0.0,196.0,1.0,21.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 18:31:21
87030,2011-05-24 18:31:25,241.87,37.89,0.0,0.0,195.0,0.0,21.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 18:31:25
87031,2011-05-24 18:31:34,241.26,38.29,0.0,0.0,196.0,0.0,24.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 18:31:34
87032,2011-05-24 18:31:37,238.87,38.03,0.0,0.0,194.0,0.0,27.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 18:31:37
87033,2011-05-24 18:31:41,240.12,38.03,0.0,0.0,198.0,0.0,22.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 18:31:41
87034,2011-05-24 18:31:44,240.45,37.90,0.0,0.0,195.0,1.0,24.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 18:31:44
87035,2011-05-24 18:31:48,241.69,38.10,0.0,0.0,194.0,0.0,25.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 18:31:48
87036,2011-05-24 18:31:51,239.98,38.18,0.0,0.0,197.0,1.0,22.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 18:31:51
87037,2011-05-24 18:31:55,240.25,38.25,0.0,0.0,194.0,1.0,21.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 18:31:55
87038,2011-05-24 18:31:58,239.04,38.06,0.0,0.0,194.0,0.0,21.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 18:31:58
87039,2011-05-24 18:32:01,238.89,37.96,0.0,0.0,196.0,0.0,21.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 18:32:01
87040,2011-05-24 19:55:38,238.84,38.68,0.0,0.0,189.0,0.0,28.0,21.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 19:55:38
87041,2011-05-24 19:55:42,235.99,38.45,0.0,0.0,187.0,0.0,24.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 19:55:42
87042,2011-05-24 19:55:45,236.41,38.65,0.0,0.0,187.0,0.0,24.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 19:55:45
87043,2011-05-24 19:55:49,236.58,38.48,0.0,0.0,189.0,0.0,26.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 19:55:49
87044,2011-05-24 19:55:52,239.92,38.57,0.0,0.0,190.0,0.0,27.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 19:55:52
87045,2011-05-24 19:55:56,235.61,38.30,0.0,0.0,188.0,0.0,24.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,2011-05-24 19:55:56
87046,2011-05-24 19:55:59,235.53,38.62,0.0,0.0,186.0,0.0,24.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,2011-05-24 19:55:59
87047,2011-05-24 19:56:03,234.72,38.77,0.0,0.0,187.0,1.0,26.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 19:56:03
87048,2011-05-24 19:56:06,234.47,38.67,0.0,0.0,188.0,0.0,24.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 19:56:06
87049,2011-05-24 19:56:10,235.47,38.66,0.0,0.0,188.0,1.0,24.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 19:56:10
87050,2011-05-24 19:56:13,235.42,38.51,0.0,0.0,190.0,1.0,25.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 19:56:13
87051,2011-05-24 19:56:17,235.33,38.62,0.0,0.0,188.0,1.0,25.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 19:56:17
87052,2011-05-24 19:56:20,235.73,38.65,0.0,0.0,186.0,1.0,26.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 19:56:20
87053,2011-05-24 19:56:23,235.03,38.66,0.0,0.0,187.0,0.0,24.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 19:56:23
87054,2011-05-24 19:56:27,235.46,38.61,0.0,0.0,190.0,0.0,24.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 19:56:27
87055,2011-05-24 19:56:30,235.98,38.77,0.0,0.0,189.0,0.0,24.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 19:56:30
87056,2011-05-24 19:56:34,235.29,38.83,0.0,0.0,186.0,0.0,26.0,20.0,2.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2011-05-24 19:56:34

In [23]:
df2 = pd.read_csv('train_test_data/H2_test_full.csv')

In [24]:
df2.head()

,Unnamed: 0,mains_1,mains_2,kitchen_outlets_3,lighting_4,stove_5,microwave_6,washer_dryer_7,kitchen_outlets_8,refrigerator_9,dishwaser_10,disposal_11
0,2011-04-18 05:31:40,15.71,22.61,1.0,8.0,1.0,4.0,4.0,4.0,6.0,1.0,0.0
1,2011-04-18 05:31:44,15.71,22.61,0.0,8.0,1.0,5.0,5.0,4.0,6.0,0.0,0.0
2,2011-04-18 05:31:47,15.72,22.61,1.0,8.0,1.0,4.0,4.0,4.0,6.0,1.0,0.0
3,2011-04-18 05:31:50,15.70,22.57,0.0,8.0,1.0,4.0,4.0,3.0,7.0,0.0,0.0
4,2011-04-18 05:32:05,15.64,22.61,1.0,8.0,1.0,4.0,4.0,3.0,7.0,1.0,0.0